// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_1rzIvVD4Lv3XNFvk0Xeh3YmJTXsS4k',
    appId: '1:309304960212:web:2dd80c56422ed5f02e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    authDomain: 'tap-map-6c884.firebaseapp.com',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    measurementId: 'G-GHQ5M910LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf1gBR96e1qgKr1rvZIA7POxvGS2caVk8',
    appId: '1:309304960212:android:7e490a4256c8f9b72e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4TJcm0oz3_3Xk3fVXrXW9fi4gJMqddY',
    appId: '1:309304960212:ios:25ed7997442f37e02e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    iosBundleId: 'com.example.tapMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4TJcm0oz3_3Xk3fVXrXW9fi4gJMqddY',
    appId: '1:309304960212:ios:25ed7997442f37e02e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    iosBundleId: 'com.example.tapMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_1rzIvVD4Lv3XNFvk0Xeh3YmJTXsS4k',
    appId: '1:309304960212:web:3e05597ee45638012e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    authDomain: 'tap-map-6c884.firebaseapp.com',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    measurementId: 'G-X6QF89XSC4',
  );
}
