name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: '3.27.0'
      APP_NAME: ${{ github.repository }}
      BASE_HREF: "/tapmap/"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Set up environment
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter pub get

    - name: Build the web app
      run: flutter build web --web-renderer html --release --base-href="${{ env.BASE_HREF }}"

    - name: Modify built index.html to include Mapbox GL JS
      run: |
        sed -i '/<\/head>/i \
        <script src="https://api.mapbox.com/mapbox-gl-js/v3.9.2/mapbox-gl.js"></script>\n\
        <link href="https://api.mapbox.com/mapbox-gl-js/v3.9.2/mapbox-gl.css" rel="stylesheet" />' build/web/index.html

    - name: Add custom Mapbox GL styles to built app
      run: |
        sed -i '/<\/style>/i \
        .mapboxgl-map {\n\
          position: relative;\n\
          width: 100%;\n\
          height: 100%;\n\
        }\n' build/web/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web