name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: '3.27.1'
      APP_NAME: ${{ github.repository }}
      BASE_HREF: "/tapmap/"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Set up environment
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter pub get

    - name: Generate splash screen
      run: flutter pub run flutter_native_splash:create

    - name: Add web icons
      run: |
        sed -i '/<\/head>/i \
        <link rel="apple-touch-icon" sizes="180x180" href="assets/web/apple-touch-icon.png">\n\
        <link rel="icon" type="image/png" sizes="192x192" href="assets/web/icon-192.png">\n\
        <link rel="icon" type="image/png" sizes="512x512" href="assets/web/icon-512.png">\n\
        <link rel="icon" type="image/png" sizes="192x192" href="assets/web/icon-192-maskable.png" mask="true">\n\
        <link rel="icon" type="image/png" sizes="512x512" href="assets/web/icon-512-maskable.png" mask="true">\n\
        <link rel="icon" type="image/x-icon" href="assets/web/favicon.ico">' web/index.html

    - name: Modify index.html to include Mapbox GL JS
      run: |
        sed -i '/<\/head>/i \
        <script src="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js"></script>\n\
        <link href="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css" rel="stylesheet" />' web/index.html

    - name: Build the web app
      run: flutter build web --base-href="${{ env.BASE_HREF }}"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
